site_name: FiveM Scripts Documentation
site_url: https://username.github.io/fivem-scripts-docs
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
nav:
  - Loan System:
      - Überblick: docs/loan_system/index.md
      - Konfiguration: docs/loan_system/config.md
      - Admin: docs/loan_system/admin.md
      - Developer: docs/loan_system/developer.md
      - Locales: docs/loan_system/locales.md
  - Script 2:
      - Überblick: docs/script_2/index.md
      - Features: docs/script_2/features.md
      - Commands: docs/script_2/commands.md
